### ISSUE TITLE
Empty repository

### ISSUE THREAD

**Issue by erikgahner** [justinsavoie/text_syllabi_analysis#1]
Great paper! A minor issue. Footnote 2 in the PS paper says "Replication material available at GitHub.com/justinsavoie/text_syllabi_analysis." However, the repository is empty.

**Comment by justinsavoie** [comment]
Hi Erik,

Thanks for the good words. I was sure everything was there, but apparently I never committed. Anyways, it's there now!

Justin

**Comment by erikgahner** [comment]
That's perfect, thanks. I can confirm that it's all there :-)
